<?php



/**
 * This class defines the structure of the 'proyecto' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 08/09/19 22:15:16
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class ProyectoTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.ProyectoTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('proyecto');
        $this->setPhpName('Proyecto');
        $this->setClassname('Proyecto');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('CODIGO', 'Codigo', 'VARCHAR', false, 50, null);
        $this->addColumn('NOMBRE', 'Nombre', 'VARCHAR', false, 350, null);
        $this->addColumn('TELEFONO', 'Telefono', 'VARCHAR', false, 50, null);
        $this->addColumn('CONTACTO', 'Contacto', 'VARCHAR', false, 50, null);
        $this->addColumn('CREATED_BY', 'CreatedBy', 'VARCHAR', false, 50, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'VARCHAR', false, 50, null);
        $this->addColumn('UPDATED_BY', 'UpdatedBy', 'VARCHAR', false, 50, null);
        $this->addColumn('UPDATED_AT', 'UpdatedAt', 'VARCHAR', false, 50, null);
        $this->addColumn('NIT_PROYECTO', 'NitProyecto', 'VARCHAR', false, 50, null);
        $this->addColumn('RAZON_SOCIAL', 'RazonSocial', 'VARCHAR', false, 350, null);
        $this->addColumn('NOMENCLATURA', 'Nomenclatura', 'VARCHAR', false, 50, null);
        $this->addColumn('UBICACION_GEOGRAFICA', 'UbicacionGeografica', 'VARCHAR', false, 50, null);
        $this->addColumn('DOCUMENTO_REPRESENTANTE', 'DocumentoRepresentante', 'VARCHAR', false, 350, null);
        $this->addColumn('REPRESENTANTE_LEGAL', 'RepresentanteLegal', 'VARCHAR', false, 350, null);
        $this->addColumn('GERENTE', 'Gerente', 'VARCHAR', false, 350, null);
        $this->addColumn('RESIDENTE', 'Residente', 'VARCHAR', false, 350, null);
        $this->addColumn('DEPARTAMENTO', 'Departamento', 'VARCHAR', false, 350, null);
        $this->addColumn('MUNICIPIO', 'Municipio', 'VARCHAR', false, 350, null);
        $this->addColumn('INTERNO', 'Interno', 'VARCHAR', false, 50, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
        );
    } // getBehaviors()

} // ProyectoTableMap
