<?php


/**
 * Base class that represents a row from the 'asistencia_usuario' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 06/20/19 17:40:56
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseAsistenciaUsuario extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'AsistenciaUsuarioPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        AsistenciaUsuarioPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the empresa field.
     * @var        string
     */
    protected $empresa;

    /**
     * The value for the usuario field.
     * @var        string
     */
    protected $usuario;

    /**
     * The value for the dia field.
     * @var        string
     */
    protected $dia;

    /**
     * The value for the hora field.
     * @var        string
     */
    protected $hora;

    /**
     * The value for the fecha_hora field.
     * @var        string
     */
    protected $fecha_hora;

    /**
     * The value for the tarde field.
     * Note: this column has a database default value of: true
     * @var        boolean
     */
    protected $tarde;

    /**
     * The value for the hora_tarde field.
     * @var        double
     */
    protected $hora_tarde;

    /**
     * The value for the minuto_tarde field.
     * @var        double
     */
    protected $minuto_tarde;

    /**
     * The value for the hora_diaria field.
     * @var        double
     */
    protected $hora_diaria;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * Applies default values to this object.
     * This method should be called from the object's constructor (or
     * equivalent initialization method).
     * @see        __construct()
     */
    public function applyDefaultValues()
    {
        $this->tarde = true;
    }

    /**
     * Initializes internal state of BaseAsistenciaUsuario object.
     * @see        applyDefaults()
     */
    public function __construct()
    {
        parent::__construct();
        $this->applyDefaultValues();
    }

    /**
     * Get the [id] column value.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the [empresa] column value.
     *
     * @return string
     */
    public function getEmpresa()
    {
        return $this->empresa;
    }

    /**
     * Get the [usuario] column value.
     *
     * @return string
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    /**
     * Get the [optionally formatted] temporal [dia] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getDia($format = 'Y-m-d')
    {
        if ($this->dia === null) {
            return null;
        }

        if ($this->dia === '0000-00-00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->dia);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->dia, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Get the [hora] column value.
     *
     * @return string
     */
    public function getHora()
    {
        return $this->hora;
    }

    /**
     * Get the [optionally formatted] temporal [fecha_hora] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getFechaHora($format = 'Y-m-d H:i:s')
    {
        if ($this->fecha_hora === null) {
            return null;
        }

        if ($this->fecha_hora === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->fecha_hora);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_hora, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Get the [tarde] column value.
     *
     * @return boolean
     */
    public function getTarde()
    {
        return $this->tarde;
    }

    /**
     * Get the [hora_tarde] column value.
     *
     * @return double
     */
    public function getHoraTarde()
    {
        return $this->hora_tarde;
    }

    /**
     * Get the [minuto_tarde] column value.
     *
     * @return double
     */
    public function getMinutoTarde()
    {
        return $this->minuto_tarde;
    }

    /**
     * Get the [hora_diaria] column value.
     *
     * @return double
     */
    public function getHoraDiaria()
    {
        return $this->hora_diaria;
    }

    /**
     * Set the value of [id] column.
     *
     * @param int $v new value
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = AsistenciaUsuarioPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [empresa] column.
     *
     * @param string $v new value
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setEmpresa($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->empresa !== $v) {
            $this->empresa = $v;
            $this->modifiedColumns[] = AsistenciaUsuarioPeer::EMPRESA;
        }


        return $this;
    } // setEmpresa()

    /**
     * Set the value of [usuario] column.
     *
     * @param string $v new value
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setUsuario($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->usuario !== $v) {
            $this->usuario = $v;
            $this->modifiedColumns[] = AsistenciaUsuarioPeer::USUARIO;
        }


        return $this;
    } // setUsuario()

    /**
     * Sets the value of [dia] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setDia($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->dia !== null || $dt !== null) {
            $currentDateAsString = ($this->dia !== null && $tmpDt = new DateTime($this->dia)) ? $tmpDt->format('Y-m-d') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->dia = $newDateAsString;
                $this->modifiedColumns[] = AsistenciaUsuarioPeer::DIA;
            }
        } // if either are not null


        return $this;
    } // setDia()

    /**
     * Set the value of [hora] column.
     *
     * @param string $v new value
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setHora($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->hora !== $v) {
            $this->hora = $v;
            $this->modifiedColumns[] = AsistenciaUsuarioPeer::HORA;
        }


        return $this;
    } // setHora()

    /**
     * Sets the value of [fecha_hora] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setFechaHora($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->fecha_hora !== null || $dt !== null) {
            $currentDateAsString = ($this->fecha_hora !== null && $tmpDt = new DateTime($this->fecha_hora)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->fecha_hora = $newDateAsString;
                $this->modifiedColumns[] = AsistenciaUsuarioPeer::FECHA_HORA;
            }
        } // if either are not null


        return $this;
    } // setFechaHora()

    /**
     * Sets the value of the [tarde] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setTarde($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->tarde !== $v) {
            $this->tarde = $v;
            $this->modifiedColumns[] = AsistenciaUsuarioPeer::TARDE;
        }


        return $this;
    } // setTarde()

    /**
     * Set the value of [hora_tarde] column.
     *
     * @param double $v new value
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setHoraTarde($v)
    {
        if ($v !== null) {
            $v = (double) $v;
        }

        if ($this->hora_tarde !== $v) {
            $this->hora_tarde = $v;
            $this->modifiedColumns[] = AsistenciaUsuarioPeer::HORA_TARDE;
        }


        return $this;
    } // setHoraTarde()

    /**
     * Set the value of [minuto_tarde] column.
     *
     * @param double $v new value
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setMinutoTarde($v)
    {
        if ($v !== null) {
            $v = (double) $v;
        }

        if ($this->minuto_tarde !== $v) {
            $this->minuto_tarde = $v;
            $this->modifiedColumns[] = AsistenciaUsuarioPeer::MINUTO_TARDE;
        }


        return $this;
    } // setMinutoTarde()

    /**
     * Set the value of [hora_diaria] column.
     *
     * @param double $v new value
     * @return AsistenciaUsuario The current object (for fluent API support)
     */
    public function setHoraDiaria($v)
    {
        if ($v !== null) {
            $v = (double) $v;
        }

        if ($this->hora_diaria !== $v) {
            $this->hora_diaria = $v;
            $this->modifiedColumns[] = AsistenciaUsuarioPeer::HORA_DIARIA;
        }


        return $this;
    } // setHoraDiaria()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
            if ($this->tarde !== true) {
                return false;
            }

        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->empresa = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
            $this->usuario = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
            $this->dia = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
            $this->hora = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
            $this->fecha_hora = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
            $this->tarde = ($row[$startcol + 6] !== null) ? (boolean) $row[$startcol + 6] : null;
            $this->hora_tarde = ($row[$startcol + 7] !== null) ? (double) $row[$startcol + 7] : null;
            $this->minuto_tarde = ($row[$startcol + 8] !== null) ? (double) $row[$startcol + 8] : null;
            $this->hora_diaria = ($row[$startcol + 9] !== null) ? (double) $row[$startcol + 9] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 10; // 10 = AsistenciaUsuarioPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating AsistenciaUsuario object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(AsistenciaUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = AsistenciaUsuarioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(AsistenciaUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = AsistenciaUsuarioQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseAsistenciaUsuario:delete:pre') as $callable)
            {
              if (call_user_func($callable, $this, $con))
              {
                $con->commit();
                return;
              }
            }

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseAsistenciaUsuario:delete:post') as $callable)
                {
                  call_user_func($callable, $this, $con);
                }

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(AsistenciaUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseAsistenciaUsuario:save:pre') as $callable)
            {
              if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
              {
                  $con->commit();
                return $affectedRows;
              }
            }

            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseAsistenciaUsuario:save:post') as $callable)
                {
                  call_user_func($callable, $this, $con, $affectedRows);
                }

                AsistenciaUsuarioPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = AsistenciaUsuarioPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . AsistenciaUsuarioPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(AsistenciaUsuarioPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`ID`';
        }
        if ($this->isColumnModified(AsistenciaUsuarioPeer::EMPRESA)) {
            $modifiedColumns[':p' . $index++]  = '`EMPRESA`';
        }
        if ($this->isColumnModified(AsistenciaUsuarioPeer::USUARIO)) {
            $modifiedColumns[':p' . $index++]  = '`USUARIO`';
        }
        if ($this->isColumnModified(AsistenciaUsuarioPeer::DIA)) {
            $modifiedColumns[':p' . $index++]  = '`DIA`';
        }
        if ($this->isColumnModified(AsistenciaUsuarioPeer::HORA)) {
            $modifiedColumns[':p' . $index++]  = '`HORA`';
        }
        if ($this->isColumnModified(AsistenciaUsuarioPeer::FECHA_HORA)) {
            $modifiedColumns[':p' . $index++]  = '`FECHA_HORA`';
        }
        if ($this->isColumnModified(AsistenciaUsuarioPeer::TARDE)) {
            $modifiedColumns[':p' . $index++]  = '`TARDE`';
        }
        if ($this->isColumnModified(AsistenciaUsuarioPeer::HORA_TARDE)) {
            $modifiedColumns[':p' . $index++]  = '`HORA_TARDE`';
        }
        if ($this->isColumnModified(AsistenciaUsuarioPeer::MINUTO_TARDE)) {
            $modifiedColumns[':p' . $index++]  = '`MINUTO_TARDE`';
        }
        if ($this->isColumnModified(AsistenciaUsuarioPeer::HORA_DIARIA)) {
            $modifiedColumns[':p' . $index++]  = '`HORA_DIARIA`';
        }

        $sql = sprintf(
            'INSERT INTO `asistencia_usuario` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`ID`':
                        $stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`EMPRESA`':
                        $stmt->bindValue($identifier, $this->empresa, PDO::PARAM_STR);
                        break;
                    case '`USUARIO`':
                        $stmt->bindValue($identifier, $this->usuario, PDO::PARAM_STR);
                        break;
                    case '`DIA`':
                        $stmt->bindValue($identifier, $this->dia, PDO::PARAM_STR);
                        break;
                    case '`HORA`':
                        $stmt->bindValue($identifier, $this->hora, PDO::PARAM_STR);
                        break;
                    case '`FECHA_HORA`':
                        $stmt->bindValue($identifier, $this->fecha_hora, PDO::PARAM_STR);
                        break;
                    case '`TARDE`':
                        $stmt->bindValue($identifier, (int) $this->tarde, PDO::PARAM_INT);
                        break;
                    case '`HORA_TARDE`':
                        $stmt->bindValue($identifier, $this->hora_tarde, PDO::PARAM_STR);
                        break;
                    case '`MINUTO_TARDE`':
                        $stmt->bindValue($identifier, $this->minuto_tarde, PDO::PARAM_STR);
                        break;
                    case '`HORA_DIARIA`':
                        $stmt->bindValue($identifier, $this->hora_diaria, PDO::PARAM_STR);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
            $pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            if (($retval = AsistenciaUsuarioPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }



            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = AsistenciaUsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getEmpresa();
                break;
            case 2:
                return $this->getUsuario();
                break;
            case 3:
                return $this->getDia();
                break;
            case 4:
                return $this->getHora();
                break;
            case 5:
                return $this->getFechaHora();
                break;
            case 6:
                return $this->getTarde();
                break;
            case 7:
                return $this->getHoraTarde();
                break;
            case 8:
                return $this->getMinutoTarde();
                break;
            case 9:
                return $this->getHoraDiaria();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array())
    {
        if (isset($alreadyDumpedObjects['AsistenciaUsuario'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['AsistenciaUsuario'][$this->getPrimaryKey()] = true;
        $keys = AsistenciaUsuarioPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getEmpresa(),
            $keys[2] => $this->getUsuario(),
            $keys[3] => $this->getDia(),
            $keys[4] => $this->getHora(),
            $keys[5] => $this->getFechaHora(),
            $keys[6] => $this->getTarde(),
            $keys[7] => $this->getHoraTarde(),
            $keys[8] => $this->getMinutoTarde(),
            $keys[9] => $this->getHoraDiaria(),
        );

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = AsistenciaUsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setEmpresa($value);
                break;
            case 2:
                $this->setUsuario($value);
                break;
            case 3:
                $this->setDia($value);
                break;
            case 4:
                $this->setHora($value);
                break;
            case 5:
                $this->setFechaHora($value);
                break;
            case 6:
                $this->setTarde($value);
                break;
            case 7:
                $this->setHoraTarde($value);
                break;
            case 8:
                $this->setMinutoTarde($value);
                break;
            case 9:
                $this->setHoraDiaria($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = AsistenciaUsuarioPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setEmpresa($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setUsuario($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setDia($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setHora($arr[$keys[4]]);
        if (array_key_exists($keys[5], $arr)) $this->setFechaHora($arr[$keys[5]]);
        if (array_key_exists($keys[6], $arr)) $this->setTarde($arr[$keys[6]]);
        if (array_key_exists($keys[7], $arr)) $this->setHoraTarde($arr[$keys[7]]);
        if (array_key_exists($keys[8], $arr)) $this->setMinutoTarde($arr[$keys[8]]);
        if (array_key_exists($keys[9], $arr)) $this->setHoraDiaria($arr[$keys[9]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(AsistenciaUsuarioPeer::DATABASE_NAME);

        if ($this->isColumnModified(AsistenciaUsuarioPeer::ID)) $criteria->add(AsistenciaUsuarioPeer::ID, $this->id);
        if ($this->isColumnModified(AsistenciaUsuarioPeer::EMPRESA)) $criteria->add(AsistenciaUsuarioPeer::EMPRESA, $this->empresa);
        if ($this->isColumnModified(AsistenciaUsuarioPeer::USUARIO)) $criteria->add(AsistenciaUsuarioPeer::USUARIO, $this->usuario);
        if ($this->isColumnModified(AsistenciaUsuarioPeer::DIA)) $criteria->add(AsistenciaUsuarioPeer::DIA, $this->dia);
        if ($this->isColumnModified(AsistenciaUsuarioPeer::HORA)) $criteria->add(AsistenciaUsuarioPeer::HORA, $this->hora);
        if ($this->isColumnModified(AsistenciaUsuarioPeer::FECHA_HORA)) $criteria->add(AsistenciaUsuarioPeer::FECHA_HORA, $this->fecha_hora);
        if ($this->isColumnModified(AsistenciaUsuarioPeer::TARDE)) $criteria->add(AsistenciaUsuarioPeer::TARDE, $this->tarde);
        if ($this->isColumnModified(AsistenciaUsuarioPeer::HORA_TARDE)) $criteria->add(AsistenciaUsuarioPeer::HORA_TARDE, $this->hora_tarde);
        if ($this->isColumnModified(AsistenciaUsuarioPeer::MINUTO_TARDE)) $criteria->add(AsistenciaUsuarioPeer::MINUTO_TARDE, $this->minuto_tarde);
        if ($this->isColumnModified(AsistenciaUsuarioPeer::HORA_DIARIA)) $criteria->add(AsistenciaUsuarioPeer::HORA_DIARIA, $this->hora_diaria);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(AsistenciaUsuarioPeer::DATABASE_NAME);
        $criteria->add(AsistenciaUsuarioPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of AsistenciaUsuario (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setEmpresa($this->getEmpresa());
        $copyObj->setUsuario($this->getUsuario());
        $copyObj->setDia($this->getDia());
        $copyObj->setHora($this->getHora());
        $copyObj->setFechaHora($this->getFechaHora());
        $copyObj->setTarde($this->getTarde());
        $copyObj->setHoraTarde($this->getHoraTarde());
        $copyObj->setMinutoTarde($this->getMinutoTarde());
        $copyObj->setHoraDiaria($this->getHoraDiaria());
        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return AsistenciaUsuario Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return AsistenciaUsuarioPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new AsistenciaUsuarioPeer();
        }

        return self::$peer;
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->empresa = null;
        $this->usuario = null;
        $this->dia = null;
        $this->hora = null;
        $this->fecha_hora = null;
        $this->tarde = null;
        $this->hora_tarde = null;
        $this->minuto_tarde = null;
        $this->hora_diaria = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->applyDefaultValues();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
        } // if ($deep)

    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(AsistenciaUsuarioPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {

        // symfony_behaviors behavior
        if ($callable = sfMixer::getCallable('BaseAsistenciaUsuario:' . $name))
        {
          array_unshift($params, $this);
          return call_user_func_array($callable, $params);
        }


        return parent::__call($name, $params);
    }

}
