<?php


/**
 * Base static class for performing query and update operations on the 'solicitud_finquito' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 09/29/18 04:44:06
 *
 * @package propel.generator.lib.model.om
 */
abstract class BaseSolicitudFinquitoPeer
{

    /** the default database name for this class */
    const DATABASE_NAME = 'propel';

    /** the table name for this class */
    const TABLE_NAME = 'solicitud_finquito';

    /** the related Propel class for this table */
    const OM_CLASS = 'SolicitudFinquito';

    /** the related TableMap class for this table */
    const TM_CLASS = 'SolicitudFinquitoTableMap';

    /** The total number of columns. */
    const NUM_COLUMNS = 14;

    /** The number of lazy-loaded columns. */
    const NUM_LAZY_LOAD_COLUMNS = 0;

    /** The number of columns to hydrate (NUM_COLUMNS - NUM_LAZY_LOAD_COLUMNS) */
    const NUM_HYDRATE_COLUMNS = 14;

    /** the column name for the ID field */
    const ID = 'solicitud_finquito.ID';

    /** the column name for the USUARIO_GRABA field */
    const USUARIO_GRABA = 'solicitud_finquito.USUARIO_GRABA';

    /** the column name for the USUARIO_RETIRO field */
    const USUARIO_RETIRO = 'solicitud_finquito.USUARIO_RETIRO';

    /** the column name for the FECHA_RETIRO field */
    const FECHA_RETIRO = 'solicitud_finquito.FECHA_RETIRO';

    /** the column name for the MOTIVO field */
    const MOTIVO = 'solicitud_finquito.MOTIVO';

    /** the column name for the OBSERVACIONES field */
    const OBSERVACIONES = 'solicitud_finquito.OBSERVACIONES';

    /** the column name for the ESTADO field */
    const ESTADO = 'solicitud_finquito.ESTADO';

    /** the column name for the CREATED_AT field */
    const CREATED_AT = 'solicitud_finquito.CREATED_AT';

    /** the column name for the UPDATED_AT field */
    const UPDATED_AT = 'solicitud_finquito.UPDATED_AT';

    /** the column name for the JEFE field */
    const JEFE = 'solicitud_finquito.JEFE';

    /** the column name for the USUARIO_MODERO field */
    const USUARIO_MODERO = 'solicitud_finquito.USUARIO_MODERO';

    /** the column name for the COMENTARIO_MODERO field */
    const COMENTARIO_MODERO = 'solicitud_finquito.COMENTARIO_MODERO';

    /** the column name for the ARCHIVO_UNO field */
    const ARCHIVO_UNO = 'solicitud_finquito.ARCHIVO_UNO';

    /** the column name for the ARCHIVO_DOS field */
    const ARCHIVO_DOS = 'solicitud_finquito.ARCHIVO_DOS';

    /** The default string format for model objects of the related table **/
    const DEFAULT_STRING_FORMAT = 'YAML';

    /**
     * An identiy map to hold any loaded instances of SolicitudFinquito objects.
     * This must be public so that other peer classes can access this when hydrating from JOIN
     * queries.
     * @var        array SolicitudFinquito[]
     */
    public static $instances = array();


    /**
     * holds an array of fieldnames
     *
     * first dimension keys are the type constants
     * e.g. SolicitudFinquitoPeer::$fieldNames[SolicitudFinquitoPeer::TYPE_PHPNAME][0] = 'Id'
     */
    protected static $fieldNames = array (
        BasePeer::TYPE_PHPNAME => array ('Id', 'UsuarioGraba', 'UsuarioRetiro', 'FechaRetiro', 'Motivo', 'Observaciones', 'Estado', 'CreatedAt', 'UpdatedAt', 'Jefe', 'UsuarioModero', 'ComentarioModero', 'ArchivoUno', 'ArchivoDos', ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'usuarioGraba', 'usuarioRetiro', 'fechaRetiro', 'motivo', 'observaciones', 'estado', 'createdAt', 'updatedAt', 'jefe', 'usuarioModero', 'comentarioModero', 'archivoUno', 'archivoDos', ),
        BasePeer::TYPE_COLNAME => array (SolicitudFinquitoPeer::ID, SolicitudFinquitoPeer::USUARIO_GRABA, SolicitudFinquitoPeer::USUARIO_RETIRO, SolicitudFinquitoPeer::FECHA_RETIRO, SolicitudFinquitoPeer::MOTIVO, SolicitudFinquitoPeer::OBSERVACIONES, SolicitudFinquitoPeer::ESTADO, SolicitudFinquitoPeer::CREATED_AT, SolicitudFinquitoPeer::UPDATED_AT, SolicitudFinquitoPeer::JEFE, SolicitudFinquitoPeer::USUARIO_MODERO, SolicitudFinquitoPeer::COMENTARIO_MODERO, SolicitudFinquitoPeer::ARCHIVO_UNO, SolicitudFinquitoPeer::ARCHIVO_DOS, ),
        BasePeer::TYPE_RAW_COLNAME => array ('ID', 'USUARIO_GRABA', 'USUARIO_RETIRO', 'FECHA_RETIRO', 'MOTIVO', 'OBSERVACIONES', 'ESTADO', 'CREATED_AT', 'UPDATED_AT', 'JEFE', 'USUARIO_MODERO', 'COMENTARIO_MODERO', 'ARCHIVO_UNO', 'ARCHIVO_DOS', ),
        BasePeer::TYPE_FIELDNAME => array ('id', 'usuario_graba', 'usuario_retiro', 'fecha_retiro', 'motivo', 'observaciones', 'estado', 'created_at', 'updated_at', 'jefe', 'usuario_modero', 'comentario_modero', 'archivo_uno', 'archivo_dos', ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, )
    );

    /**
     * holds an array of keys for quick access to the fieldnames array
     *
     * first dimension keys are the type constants
     * e.g. SolicitudFinquitoPeer::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
     */
    protected static $fieldKeys = array (
        BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'UsuarioGraba' => 1, 'UsuarioRetiro' => 2, 'FechaRetiro' => 3, 'Motivo' => 4, 'Observaciones' => 5, 'Estado' => 6, 'CreatedAt' => 7, 'UpdatedAt' => 8, 'Jefe' => 9, 'UsuarioModero' => 10, 'ComentarioModero' => 11, 'ArchivoUno' => 12, 'ArchivoDos' => 13, ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'usuarioGraba' => 1, 'usuarioRetiro' => 2, 'fechaRetiro' => 3, 'motivo' => 4, 'observaciones' => 5, 'estado' => 6, 'createdAt' => 7, 'updatedAt' => 8, 'jefe' => 9, 'usuarioModero' => 10, 'comentarioModero' => 11, 'archivoUno' => 12, 'archivoDos' => 13, ),
        BasePeer::TYPE_COLNAME => array (SolicitudFinquitoPeer::ID => 0, SolicitudFinquitoPeer::USUARIO_GRABA => 1, SolicitudFinquitoPeer::USUARIO_RETIRO => 2, SolicitudFinquitoPeer::FECHA_RETIRO => 3, SolicitudFinquitoPeer::MOTIVO => 4, SolicitudFinquitoPeer::OBSERVACIONES => 5, SolicitudFinquitoPeer::ESTADO => 6, SolicitudFinquitoPeer::CREATED_AT => 7, SolicitudFinquitoPeer::UPDATED_AT => 8, SolicitudFinquitoPeer::JEFE => 9, SolicitudFinquitoPeer::USUARIO_MODERO => 10, SolicitudFinquitoPeer::COMENTARIO_MODERO => 11, SolicitudFinquitoPeer::ARCHIVO_UNO => 12, SolicitudFinquitoPeer::ARCHIVO_DOS => 13, ),
        BasePeer::TYPE_RAW_COLNAME => array ('ID' => 0, 'USUARIO_GRABA' => 1, 'USUARIO_RETIRO' => 2, 'FECHA_RETIRO' => 3, 'MOTIVO' => 4, 'OBSERVACIONES' => 5, 'ESTADO' => 6, 'CREATED_AT' => 7, 'UPDATED_AT' => 8, 'JEFE' => 9, 'USUARIO_MODERO' => 10, 'COMENTARIO_MODERO' => 11, 'ARCHIVO_UNO' => 12, 'ARCHIVO_DOS' => 13, ),
        BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'usuario_graba' => 1, 'usuario_retiro' => 2, 'fecha_retiro' => 3, 'motivo' => 4, 'observaciones' => 5, 'estado' => 6, 'created_at' => 7, 'updated_at' => 8, 'jefe' => 9, 'usuario_modero' => 10, 'comentario_modero' => 11, 'archivo_uno' => 12, 'archivo_dos' => 13, ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, )
    );

    /**
     * Translates a fieldname to another type
     *
     * @param      string $name field name
     * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @param      string $toType   One of the class type constants
     * @return string          translated name of the field.
     * @throws PropelException - if the specified name could not be found in the fieldname mappings.
     */
    public static function translateFieldName($name, $fromType, $toType)
    {
        $toNames = SolicitudFinquitoPeer::getFieldNames($toType);
        $key = isset(SolicitudFinquitoPeer::$fieldKeys[$fromType][$name]) ? SolicitudFinquitoPeer::$fieldKeys[$fromType][$name] : null;
        if ($key === null) {
            throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(SolicitudFinquitoPeer::$fieldKeys[$fromType], true));
        }

        return $toNames[$key];
    }

    /**
     * Returns an array of field names.
     *
     * @param      string $type The type of fieldnames to return:
     *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @return array           A list of field names
     * @throws PropelException - if the type is not valid.
     */
    public static function getFieldNames($type = BasePeer::TYPE_PHPNAME)
    {
        if (!array_key_exists($type, SolicitudFinquitoPeer::$fieldNames)) {
            throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
        }

        return SolicitudFinquitoPeer::$fieldNames[$type];
    }

    /**
     * Convenience method which changes table.column to alias.column.
     *
     * Using this method you can maintain SQL abstraction while using column aliases.
     * <code>
     *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
     *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
     * </code>
     * @param      string $alias The alias for the current table.
     * @param      string $column The column name for current table. (i.e. SolicitudFinquitoPeer::COLUMN_NAME).
     * @return string
     */
    public static function alias($alias, $column)
    {
        return str_replace(SolicitudFinquitoPeer::TABLE_NAME.'.', $alias.'.', $column);
    }

    /**
     * Add all the columns needed to create a new object.
     *
     * Note: any columns that were marked with lazyLoad="true" in the
     * XML schema will not be added to the select list and only loaded
     * on demand.
     *
     * @param      Criteria $criteria object containing the columns to add.
     * @param      string   $alias    optional table alias
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function addSelectColumns(Criteria $criteria, $alias = null)
    {
        if (null === $alias) {
            $criteria->addSelectColumn(SolicitudFinquitoPeer::ID);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::USUARIO_GRABA);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::USUARIO_RETIRO);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::FECHA_RETIRO);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::MOTIVO);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::OBSERVACIONES);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::ESTADO);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::CREATED_AT);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::UPDATED_AT);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::JEFE);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::USUARIO_MODERO);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::COMENTARIO_MODERO);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::ARCHIVO_UNO);
            $criteria->addSelectColumn(SolicitudFinquitoPeer::ARCHIVO_DOS);
        } else {
            $criteria->addSelectColumn($alias . '.ID');
            $criteria->addSelectColumn($alias . '.USUARIO_GRABA');
            $criteria->addSelectColumn($alias . '.USUARIO_RETIRO');
            $criteria->addSelectColumn($alias . '.FECHA_RETIRO');
            $criteria->addSelectColumn($alias . '.MOTIVO');
            $criteria->addSelectColumn($alias . '.OBSERVACIONES');
            $criteria->addSelectColumn($alias . '.ESTADO');
            $criteria->addSelectColumn($alias . '.CREATED_AT');
            $criteria->addSelectColumn($alias . '.UPDATED_AT');
            $criteria->addSelectColumn($alias . '.JEFE');
            $criteria->addSelectColumn($alias . '.USUARIO_MODERO');
            $criteria->addSelectColumn($alias . '.COMENTARIO_MODERO');
            $criteria->addSelectColumn($alias . '.ARCHIVO_UNO');
            $criteria->addSelectColumn($alias . '.ARCHIVO_DOS');
        }
    }

    /**
     * Returns the number of rows matching criteria.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @return int Number of matching rows.
     */
    public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
    {
        // we may modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(SolicitudFinquitoPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            SolicitudFinquitoPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME); // Set the correct dbName

        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }

        // BasePeer returns a PDOStatement
        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }
    /**
     * Selects one object from the DB.
     *
     * @param      Criteria $criteria object used to create the SELECT statement.
     * @param      PropelPDO $con
     * @return                 SolicitudFinquito
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
    {
        $critcopy = clone $criteria;
        $critcopy->setLimit(1);
        $objects = SolicitudFinquitoPeer::doSelect($critcopy, $con);
        if ($objects) {
            return $objects[0];
        }

        return null;
    }
    /**
     * Selects several row from the DB.
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con
     * @return array           Array of selected Objects
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelect(Criteria $criteria, PropelPDO $con = null)
    {
        return SolicitudFinquitoPeer::populateObjects(SolicitudFinquitoPeer::doSelectStmt($criteria, $con));
    }
    /**
     * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
     *
     * Use this method directly if you want to work with an executed statement durirectly (for example
     * to perform your own object hydration).
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con The connection to use
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return PDOStatement The executed PDOStatement object.
     * @see        BasePeer::doSelect()
     */
    public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        if (!$criteria->hasSelectClause()) {
            $criteria = clone $criteria;
            SolicitudFinquitoPeer::addSelectColumns($criteria);
        }

        // Set the correct dbName
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);
        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }


        // BasePeer returns a PDOStatement
        return BasePeer::doSelect($criteria, $con);
    }
    /**
     * Adds an object to the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doSelect*()
     * methods in your stub classes -- you may need to explicitly add objects
     * to the cache in order to ensure that the same objects are always returned by doSelect*()
     * and retrieveByPK*() calls.
     *
     * @param      SolicitudFinquito $obj A SolicitudFinquito object.
     * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
     */
    public static function addInstanceToPool($obj, $key = null)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if ($key === null) {
                $key = (string) $obj->getId();
            } // if key === null
            SolicitudFinquitoPeer::$instances[$key] = $obj;
        }
    }

    /**
     * Removes an object from the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doDelete
     * methods in your stub classes -- you may need to explicitly remove objects
     * from the cache in order to prevent returning objects that no longer exist.
     *
     * @param      mixed $value A SolicitudFinquito object or a primary key value.
     *
     * @return void
     * @throws PropelException - if the value is invalid.
     */
    public static function removeInstanceFromPool($value)
    {
        if (Propel::isInstancePoolingEnabled() && $value !== null) {
            if (is_object($value) && $value instanceof SolicitudFinquito) {
                $key = (string) $value->getId();
            } elseif (is_scalar($value)) {
                // assume we've been passed a primary key
                $key = (string) $value;
            } else {
                $e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or SolicitudFinquito object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
                throw $e;
            }

            unset(SolicitudFinquitoPeer::$instances[$key]);
        }
    } // removeInstanceFromPool()

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
     * @return   SolicitudFinquito Found object or null if 1) no instance exists for specified key or 2) instance pooling has been disabled.
     * @see        getPrimaryKeyHash()
     */
    public static function getInstanceFromPool($key)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if (isset(SolicitudFinquitoPeer::$instances[$key])) {
                return SolicitudFinquitoPeer::$instances[$key];
            }
        }

        return null; // just to be explicit
    }

    /**
     * Clear the instance pool.
     *
     * @return void
     */
    public static function clearInstancePool()
    {
        SolicitudFinquitoPeer::$instances = array();
    }

    /**
     * Method to invalidate the instance pool of all tables related to solicitud_finquito
     * by a foreign key with ON DELETE CASCADE
     */
    public static function clearRelatedInstancePool()
    {
    }

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return string A string version of PK or null if the components of primary key in result array are all null.
     */
    public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
    {
        // If the PK cannot be derived from the row, return null.
        if ($row[$startcol] === null) {
            return null;
        }

        return (string) $row[$startcol];
    }

    /**
     * Retrieves the primary key from the DB resultset row
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, an array of the primary key columns will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return mixed The primary key of the row
     */
    public static function getPrimaryKeyFromRow($row, $startcol = 0)
    {

        return (int) $row[$startcol];
    }

    /**
     * The returned array will contain objects of the default type or
     * objects that inherit from the default.
     *
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function populateObjects(PDOStatement $stmt)
    {
        $results = array();

        // set the class once to avoid overhead in the loop
        $cls = SolicitudFinquitoPeer::getOMClass();
        // populate the object(s)
        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key = SolicitudFinquitoPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj = SolicitudFinquitoPeer::getInstanceFromPool($key))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj->hydrate($row, 0, true); // rehydrate
                $results[] = $obj;
            } else {
                $obj = new $cls();
                $obj->hydrate($row);
                $results[] = $obj;
                SolicitudFinquitoPeer::addInstanceToPool($obj, $key);
            } // if key exists
        }
        $stmt->closeCursor();

        return $results;
    }
    /**
     * Populates an object of the default type or an object that inherit from the default.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return array (SolicitudFinquito object, last column rank)
     */
    public static function populateObject($row, $startcol = 0)
    {
        $key = SolicitudFinquitoPeer::getPrimaryKeyHashFromRow($row, $startcol);
        if (null !== ($obj = SolicitudFinquitoPeer::getInstanceFromPool($key))) {
            // We no longer rehydrate the object, since this can cause data loss.
            // See http://www.propelorm.org/ticket/509
            // $obj->hydrate($row, $startcol, true); // rehydrate
            $col = $startcol + SolicitudFinquitoPeer::NUM_HYDRATE_COLUMNS;
        } else {
            $cls = SolicitudFinquitoPeer::OM_CLASS;
            $obj = new $cls();
            $col = $obj->hydrate($row, $startcol);
            SolicitudFinquitoPeer::addInstanceToPool($obj, $key);
        }

        return array($obj, $col);
    }


    /**
     * Returns the number of rows matching criteria, joining the related UsuarioRelatedByUsuarioGraba table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinUsuarioRelatedByUsuarioGraba(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(SolicitudFinquitoPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            SolicitudFinquitoPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

        // Set the correct dbName
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria->addJoin(SolicitudFinquitoPeer::USUARIO_GRABA, UsuarioPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Returns the number of rows matching criteria, joining the related UsuarioRelatedByUsuarioRetiro table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinUsuarioRelatedByUsuarioRetiro(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(SolicitudFinquitoPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            SolicitudFinquitoPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

        // Set the correct dbName
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria->addJoin(SolicitudFinquitoPeer::USUARIO_RETIRO, UsuarioPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Selects a collection of SolicitudFinquito objects pre-filled with their Usuario objects.
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of SolicitudFinquito objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinUsuarioRelatedByUsuarioGraba(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);
        }

        SolicitudFinquitoPeer::addSelectColumns($criteria);
        $startcol = SolicitudFinquitoPeer::NUM_HYDRATE_COLUMNS;
        UsuarioPeer::addSelectColumns($criteria);

        $criteria->addJoin(SolicitudFinquitoPeer::USUARIO_GRABA, UsuarioPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }

        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = SolicitudFinquitoPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = SolicitudFinquitoPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {

                $cls = SolicitudFinquitoPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                SolicitudFinquitoPeer::addInstanceToPool($obj1, $key1);
            } // if $obj1 already loaded

            $key2 = UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol);
            if ($key2 !== null) {
                $obj2 = UsuarioPeer::getInstanceFromPool($key2);
                if (!$obj2) {

                    $cls = UsuarioPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol);
                    UsuarioPeer::addInstanceToPool($obj2, $key2);
                } // if obj2 already loaded

                // Add the $obj1 (SolicitudFinquito) to $obj2 (Usuario)
                $obj2->addSolicitudFinquitoRelatedByUsuarioGraba($obj1);

            } // if joined row was not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Selects a collection of SolicitudFinquito objects pre-filled with their Usuario objects.
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of SolicitudFinquito objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinUsuarioRelatedByUsuarioRetiro(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);
        }

        SolicitudFinquitoPeer::addSelectColumns($criteria);
        $startcol = SolicitudFinquitoPeer::NUM_HYDRATE_COLUMNS;
        UsuarioPeer::addSelectColumns($criteria);

        $criteria->addJoin(SolicitudFinquitoPeer::USUARIO_RETIRO, UsuarioPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }

        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = SolicitudFinquitoPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = SolicitudFinquitoPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {

                $cls = SolicitudFinquitoPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                SolicitudFinquitoPeer::addInstanceToPool($obj1, $key1);
            } // if $obj1 already loaded

            $key2 = UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol);
            if ($key2 !== null) {
                $obj2 = UsuarioPeer::getInstanceFromPool($key2);
                if (!$obj2) {

                    $cls = UsuarioPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol);
                    UsuarioPeer::addInstanceToPool($obj2, $key2);
                } // if obj2 already loaded

                // Add the $obj1 (SolicitudFinquito) to $obj2 (Usuario)
                $obj2->addSolicitudFinquitoRelatedByUsuarioRetiro($obj1);

            } // if joined row was not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Returns the number of rows matching criteria, joining all related tables
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(SolicitudFinquitoPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            SolicitudFinquitoPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

        // Set the correct dbName
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria->addJoin(SolicitudFinquitoPeer::USUARIO_GRABA, UsuarioPeer::ID, $join_behavior);

        $criteria->addJoin(SolicitudFinquitoPeer::USUARIO_RETIRO, UsuarioPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }

    /**
     * Selects a collection of SolicitudFinquito objects pre-filled with all related objects.
     *
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of SolicitudFinquito objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);
        }

        SolicitudFinquitoPeer::addSelectColumns($criteria);
        $startcol2 = SolicitudFinquitoPeer::NUM_HYDRATE_COLUMNS;

        UsuarioPeer::addSelectColumns($criteria);
        $startcol3 = $startcol2 + UsuarioPeer::NUM_HYDRATE_COLUMNS;

        UsuarioPeer::addSelectColumns($criteria);
        $startcol4 = $startcol3 + UsuarioPeer::NUM_HYDRATE_COLUMNS;

        $criteria->addJoin(SolicitudFinquitoPeer::USUARIO_GRABA, UsuarioPeer::ID, $join_behavior);

        $criteria->addJoin(SolicitudFinquitoPeer::USUARIO_RETIRO, UsuarioPeer::ID, $join_behavior);

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }

        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = SolicitudFinquitoPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = SolicitudFinquitoPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {
                $cls = SolicitudFinquitoPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                SolicitudFinquitoPeer::addInstanceToPool($obj1, $key1);
            } // if obj1 already loaded

            // Add objects for joined Usuario rows

            $key2 = UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
            if ($key2 !== null) {
                $obj2 = UsuarioPeer::getInstanceFromPool($key2);
                if (!$obj2) {

                    $cls = UsuarioPeer::getOMClass();

                    $obj2 = new $cls();
                    $obj2->hydrate($row, $startcol2);
                    UsuarioPeer::addInstanceToPool($obj2, $key2);
                } // if obj2 loaded

                // Add the $obj1 (SolicitudFinquito) to the collection in $obj2 (Usuario)
                $obj2->addSolicitudFinquitoRelatedByUsuarioGraba($obj1);
            } // if joined row not null

            // Add objects for joined Usuario rows

            $key3 = UsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol3);
            if ($key3 !== null) {
                $obj3 = UsuarioPeer::getInstanceFromPool($key3);
                if (!$obj3) {

                    $cls = UsuarioPeer::getOMClass();

                    $obj3 = new $cls();
                    $obj3->hydrate($row, $startcol3);
                    UsuarioPeer::addInstanceToPool($obj3, $key3);
                } // if obj3 loaded

                // Add the $obj1 (SolicitudFinquito) to the collection in $obj3 (Usuario)
                $obj3->addSolicitudFinquitoRelatedByUsuarioRetiro($obj1);
            } // if joined row not null

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Returns the number of rows matching criteria, joining the related UsuarioRelatedByUsuarioGraba table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinAllExceptUsuarioRelatedByUsuarioGraba(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(SolicitudFinquitoPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            SolicitudFinquitoPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY should not affect count

        // Set the correct dbName
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Returns the number of rows matching criteria, joining the related UsuarioRelatedByUsuarioRetiro table
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return int Number of matching rows.
     */
    public static function doCountJoinAllExceptUsuarioRelatedByUsuarioRetiro(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        // we're going to modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(SolicitudFinquitoPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            SolicitudFinquitoPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY should not affect count

        // Set the correct dbName
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);

        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }

        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }


    /**
     * Selects a collection of SolicitudFinquito objects pre-filled with all related objects except UsuarioRelatedByUsuarioGraba.
     *
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of SolicitudFinquito objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinAllExceptUsuarioRelatedByUsuarioGraba(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        // $criteria->getDbName() will return the same object if not set to another value
        // so == check is okay and faster
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);
        }

        SolicitudFinquitoPeer::addSelectColumns($criteria);
        $startcol2 = SolicitudFinquitoPeer::NUM_HYDRATE_COLUMNS;

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }


        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = SolicitudFinquitoPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = SolicitudFinquitoPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {
                $cls = SolicitudFinquitoPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                SolicitudFinquitoPeer::addInstanceToPool($obj1, $key1);
            } // if obj1 already loaded

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }


    /**
     * Selects a collection of SolicitudFinquito objects pre-filled with all related objects except UsuarioRelatedByUsuarioRetiro.
     *
     * @param      Criteria  $criteria
     * @param      PropelPDO $con
     * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
     * @return array           Array of SolicitudFinquito objects.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectJoinAllExceptUsuarioRelatedByUsuarioRetiro(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $criteria = clone $criteria;

        // Set the correct dbName if it has not been overridden
        // $criteria->getDbName() will return the same object if not set to another value
        // so == check is okay and faster
        if ($criteria->getDbName() == Propel::getDefaultDB()) {
            $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);
        }

        SolicitudFinquitoPeer::addSelectColumns($criteria);
        $startcol2 = SolicitudFinquitoPeer::NUM_HYDRATE_COLUMNS;

        // symfony_behaviors behavior
        foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
        {
          call_user_func($sf_hook, 'BaseSolicitudFinquitoPeer', $criteria, $con);
        }


        $stmt = BasePeer::doSelect($criteria, $con);
        $results = array();

        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key1 = SolicitudFinquitoPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj1 = SolicitudFinquitoPeer::getInstanceFromPool($key1))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj1->hydrate($row, 0, true); // rehydrate
            } else {
                $cls = SolicitudFinquitoPeer::getOMClass();

                $obj1 = new $cls();
                $obj1->hydrate($row);
                SolicitudFinquitoPeer::addInstanceToPool($obj1, $key1);
            } // if obj1 already loaded

            $results[] = $obj1;
        }
        $stmt->closeCursor();

        return $results;
    }

    /**
     * Returns the TableMap related to this peer.
     * This method is not needed for general use but a specific application could have a need.
     * @return TableMap
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function getTableMap()
    {
        return Propel::getDatabaseMap(SolicitudFinquitoPeer::DATABASE_NAME)->getTable(SolicitudFinquitoPeer::TABLE_NAME);
    }

    /**
     * Add a TableMap instance to the database for this peer class.
     */
    public static function buildTableMap()
    {
      $dbMap = Propel::getDatabaseMap(BaseSolicitudFinquitoPeer::DATABASE_NAME);
      if (!$dbMap->hasTable(BaseSolicitudFinquitoPeer::TABLE_NAME)) {
        $dbMap->addTableObject(new SolicitudFinquitoTableMap());
      }
    }

    /**
     * The class that the Peer will make instances of.
     *
     *
     * @return string ClassName
     */
    public static function getOMClass()
    {
        return SolicitudFinquitoPeer::OM_CLASS;
    }

    /**
     * Performs an INSERT on the database, given a SolicitudFinquito or Criteria object.
     *
     * @param      mixed $values Criteria or SolicitudFinquito object containing data that is used to create the INSERT statement.
     * @param      PropelPDO $con the PropelPDO connection to use
     * @return mixed           The new primary key.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doInsert($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity
        } else {
            $criteria = $values->buildCriteria(); // build Criteria from SolicitudFinquito object
        }

        if ($criteria->containsKey(SolicitudFinquitoPeer::ID) && $criteria->keyContainsValue(SolicitudFinquitoPeer::ID) ) {
            throw new PropelException('Cannot insert a value for auto-increment primary key ('.SolicitudFinquitoPeer::ID.')');
        }


        // Set the correct dbName
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);

        try {
            // use transaction because $criteria could contain info
            // for more than one table (I guess, conceivably)
            $con->beginTransaction();
            $pk = BasePeer::doInsert($criteria, $con);
            $con->commit();
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }

        return $pk;
    }

    /**
     * Performs an UPDATE on the database, given a SolicitudFinquito or Criteria object.
     *
     * @param      mixed $values Criteria or SolicitudFinquito object containing data that is used to create the UPDATE statement.
     * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doUpdate($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $selectCriteria = new Criteria(SolicitudFinquitoPeer::DATABASE_NAME);

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity

            $comparison = $criteria->getComparison(SolicitudFinquitoPeer::ID);
            $value = $criteria->remove(SolicitudFinquitoPeer::ID);
            if ($value) {
                $selectCriteria->add(SolicitudFinquitoPeer::ID, $value, $comparison);
            } else {
                $selectCriteria->setPrimaryTableName(SolicitudFinquitoPeer::TABLE_NAME);
            }

        } else { // $values is SolicitudFinquito object
            $criteria = $values->buildCriteria(); // gets full criteria
            $selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
        }

        // set the correct dbName
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);

        return BasePeer::doUpdate($selectCriteria, $criteria, $con);
    }

    /**
     * Deletes all rows from the solicitud_finquito table.
     *
     * @param      PropelPDO $con the connection to use
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException
     */
    public static function doDeleteAll(PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }
        $affectedRows = 0; // initialize var to track total num of affected rows
        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();
            $affectedRows += BasePeer::doDeleteAll(SolicitudFinquitoPeer::TABLE_NAME, $con, SolicitudFinquitoPeer::DATABASE_NAME);
            // Because this db requires some delete cascade/set null emulation, we have to
            // clear the cached instance *after* the emulation has happened (since
            // instances get re-added by the select statement contained therein).
            SolicitudFinquitoPeer::clearInstancePool();
            SolicitudFinquitoPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs a DELETE on the database, given a SolicitudFinquito or Criteria object OR a primary key value.
     *
     * @param      mixed $values Criteria or SolicitudFinquito object or primary key or array of primary keys
     *              which is used to create the DELETE statement
     * @param      PropelPDO $con the connection to use
     * @return int The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
     *				if supported by native driver or if emulated using Propel.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
     public static function doDelete($values, PropelPDO $con = null)
     {
        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            // invalidate the cache for all objects of this type, since we have no
            // way of knowing (without running a query) what objects should be invalidated
            // from the cache based on this Criteria.
            SolicitudFinquitoPeer::clearInstancePool();
            // rename for clarity
            $criteria = clone $values;
        } elseif ($values instanceof SolicitudFinquito) { // it's a model object
            // invalidate the cache for this single object
            SolicitudFinquitoPeer::removeInstanceFromPool($values);
            // create criteria based on pk values
            $criteria = $values->buildPkeyCriteria();
        } else { // it's a primary key, or an array of pks
            $criteria = new Criteria(SolicitudFinquitoPeer::DATABASE_NAME);
            $criteria->add(SolicitudFinquitoPeer::ID, (array) $values, Criteria::IN);
            // invalidate the cache for this object(s)
            foreach ((array) $values as $singleval) {
                SolicitudFinquitoPeer::removeInstanceFromPool($singleval);
            }
        }

        // Set the correct dbName
        $criteria->setDbName(SolicitudFinquitoPeer::DATABASE_NAME);

        $affectedRows = 0; // initialize var to track total num of affected rows

        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();

            $affectedRows += BasePeer::doDelete($criteria, $con);
            SolicitudFinquitoPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Validates all modified columns of given SolicitudFinquito object.
     * If parameter $columns is either a single column name or an array of column names
     * than only those columns are validated.
     *
     * NOTICE: This does not apply to primary or foreign keys for now.
     *
     * @param      SolicitudFinquito $obj The object to validate.
     * @param      mixed $cols Column name or array of column names.
     *
     * @return mixed TRUE if all columns are valid or the error message of the first invalid column.
     */
    public static function doValidate($obj, $cols = null)
    {
        $columns = array();

        if ($cols) {
            $dbMap = Propel::getDatabaseMap(SolicitudFinquitoPeer::DATABASE_NAME);
            $tableMap = $dbMap->getTable(SolicitudFinquitoPeer::TABLE_NAME);

            if (! is_array($cols)) {
                $cols = array($cols);
            }

            foreach ($cols as $colName) {
                if ($tableMap->hasColumn($colName)) {
                    $get = 'get' . $tableMap->getColumn($colName)->getPhpName();
                    $columns[$colName] = $obj->$get();
                }
            }
        } else {

        }

        return BasePeer::doValidate(SolicitudFinquitoPeer::DATABASE_NAME, SolicitudFinquitoPeer::TABLE_NAME, $columns);
    }

    /**
     * Retrieve a single object by pkey.
     *
     * @param      int $pk the primary key.
     * @param      PropelPDO $con the connection to use
     * @return SolicitudFinquito
     */
    public static function retrieveByPK($pk, PropelPDO $con = null)
    {

        if (null !== ($obj = SolicitudFinquitoPeer::getInstanceFromPool((string) $pk))) {
            return $obj;
        }

        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria = new Criteria(SolicitudFinquitoPeer::DATABASE_NAME);
        $criteria->add(SolicitudFinquitoPeer::ID, $pk);

        $v = SolicitudFinquitoPeer::doSelect($criteria, $con);

        return !empty($v) > 0 ? $v[0] : null;
    }

    /**
     * Retrieve multiple objects by pkey.
     *
     * @param      array $pks List of primary keys
     * @param      PropelPDO $con the connection to use
     * @return SolicitudFinquito[]
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function retrieveByPKs($pks, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(SolicitudFinquitoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $objs = null;
        if (empty($pks)) {
            $objs = array();
        } else {
            $criteria = new Criteria(SolicitudFinquitoPeer::DATABASE_NAME);
            $criteria->add(SolicitudFinquitoPeer::ID, $pks, Criteria::IN);
            $objs = SolicitudFinquitoPeer::doSelect($criteria, $con);
        }

        return $objs;
    }

    // symfony behavior

    /**
     * Returns an array of arrays that contain columns in each unique index.
     *
     * @return array
     */
    static public function getUniqueColumnNames()
    {
      return array();
    }

    // symfony_behaviors behavior

    /**
     * Returns the name of the hook to call from inside the supplied method.
     *
     * @param string $method The calling method
     *
     * @return string A hook name for {@link sfMixer}
     *
     * @throws LogicException If the method name is not recognized
     */
    static private function getMixerPreSelectHook($method)
    {
      if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
      {
        return sprintf('BaseSolicitudFinquitoPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
      }

      throw new LogicException(sprintf('Unrecognized function "%s"', $method));
    }

} // BaseSolicitudFinquitoPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseSolicitudFinquitoPeer::buildTableMap();

