<?php


/**
 * Base class that represents a row from the 'vacacion_usuario' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 10/07/18 01:54:16
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseVacacionUsuario extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'VacacionUsuarioPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        VacacionUsuarioPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the usuario_id field.
     * @var        int
     */
    protected $usuario_id;

    /**
     * The value for the periodo field.
     * @var        int
     */
    protected $periodo;

    /**
     * The value for the fecha_inicio field.
     * @var        string
     */
    protected $fecha_inicio;

    /**
     * The value for the fecha_fin field.
     * @var        string
     */
    protected $fecha_fin;

    /**
     * The value for the valor field.
     * @var        double
     */
    protected $valor;

    /**
     * The value for the dias field.
     * @var        int
     */
    protected $dias;

    /**
     * The value for the observaciones field.
     * @var        string
     */
    protected $observaciones;

    /**
     * The value for the archivo_uno field.
     * @var        string
     */
    protected $archivo_uno;

    /**
     * The value for the archivo_dos field.
     * @var        string
     */
    protected $archivo_dos;

    /**
     * @var        Usuario
     */
    protected $aUsuario;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * Get the [id] column value.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the [usuario_id] column value.
     *
     * @return int
     */
    public function getUsuarioId()
    {
        return $this->usuario_id;
    }

    /**
     * Get the [periodo] column value.
     *
     * @return int
     */
    public function getPeriodo()
    {
        return $this->periodo;
    }

    /**
     * Get the [optionally formatted] temporal [fecha_inicio] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getFechaInicio($format = 'Y-m-d')
    {
        if ($this->fecha_inicio === null) {
            return null;
        }

        if ($this->fecha_inicio === '0000-00-00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->fecha_inicio);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_inicio, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Get the [optionally formatted] temporal [fecha_fin] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getFechaFin($format = 'Y-m-d')
    {
        if ($this->fecha_fin === null) {
            return null;
        }

        if ($this->fecha_fin === '0000-00-00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->fecha_fin);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_fin, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Get the [valor] column value.
     *
     * @return double
     */
    public function getValor()
    {
        return $this->valor;
    }

    /**
     * Get the [dias] column value.
     *
     * @return int
     */
    public function getDias()
    {
        return $this->dias;
    }

    /**
     * Get the [observaciones] column value.
     *
     * @return string
     */
    public function getObservaciones()
    {
        return $this->observaciones;
    }

    /**
     * Get the [archivo_uno] column value.
     *
     * @return string
     */
    public function getArchivoUno()
    {
        return $this->archivo_uno;
    }

    /**
     * Get the [archivo_dos] column value.
     *
     * @return string
     */
    public function getArchivoDos()
    {
        return $this->archivo_dos;
    }

    /**
     * Set the value of [id] column.
     *
     * @param int $v new value
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = VacacionUsuarioPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [usuario_id] column.
     *
     * @param int $v new value
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setUsuarioId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->usuario_id !== $v) {
            $this->usuario_id = $v;
            $this->modifiedColumns[] = VacacionUsuarioPeer::USUARIO_ID;
        }

        if ($this->aUsuario !== null && $this->aUsuario->getId() !== $v) {
            $this->aUsuario = null;
        }


        return $this;
    } // setUsuarioId()

    /**
     * Set the value of [periodo] column.
     *
     * @param int $v new value
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setPeriodo($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->periodo !== $v) {
            $this->periodo = $v;
            $this->modifiedColumns[] = VacacionUsuarioPeer::PERIODO;
        }


        return $this;
    } // setPeriodo()

    /**
     * Sets the value of [fecha_inicio] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setFechaInicio($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->fecha_inicio !== null || $dt !== null) {
            $currentDateAsString = ($this->fecha_inicio !== null && $tmpDt = new DateTime($this->fecha_inicio)) ? $tmpDt->format('Y-m-d') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->fecha_inicio = $newDateAsString;
                $this->modifiedColumns[] = VacacionUsuarioPeer::FECHA_INICIO;
            }
        } // if either are not null


        return $this;
    } // setFechaInicio()

    /**
     * Sets the value of [fecha_fin] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setFechaFin($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->fecha_fin !== null || $dt !== null) {
            $currentDateAsString = ($this->fecha_fin !== null && $tmpDt = new DateTime($this->fecha_fin)) ? $tmpDt->format('Y-m-d') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->fecha_fin = $newDateAsString;
                $this->modifiedColumns[] = VacacionUsuarioPeer::FECHA_FIN;
            }
        } // if either are not null


        return $this;
    } // setFechaFin()

    /**
     * Set the value of [valor] column.
     *
     * @param double $v new value
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setValor($v)
    {
        if ($v !== null) {
            $v = (double) $v;
        }

        if ($this->valor !== $v) {
            $this->valor = $v;
            $this->modifiedColumns[] = VacacionUsuarioPeer::VALOR;
        }


        return $this;
    } // setValor()

    /**
     * Set the value of [dias] column.
     *
     * @param int $v new value
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setDias($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->dias !== $v) {
            $this->dias = $v;
            $this->modifiedColumns[] = VacacionUsuarioPeer::DIAS;
        }


        return $this;
    } // setDias()

    /**
     * Set the value of [observaciones] column.
     *
     * @param string $v new value
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setObservaciones($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->observaciones !== $v) {
            $this->observaciones = $v;
            $this->modifiedColumns[] = VacacionUsuarioPeer::OBSERVACIONES;
        }


        return $this;
    } // setObservaciones()

    /**
     * Set the value of [archivo_uno] column.
     *
     * @param string $v new value
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setArchivoUno($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->archivo_uno !== $v) {
            $this->archivo_uno = $v;
            $this->modifiedColumns[] = VacacionUsuarioPeer::ARCHIVO_UNO;
        }


        return $this;
    } // setArchivoUno()

    /**
     * Set the value of [archivo_dos] column.
     *
     * @param string $v new value
     * @return VacacionUsuario The current object (for fluent API support)
     */
    public function setArchivoDos($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->archivo_dos !== $v) {
            $this->archivo_dos = $v;
            $this->modifiedColumns[] = VacacionUsuarioPeer::ARCHIVO_DOS;
        }


        return $this;
    } // setArchivoDos()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->usuario_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
            $this->periodo = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
            $this->fecha_inicio = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
            $this->fecha_fin = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
            $this->valor = ($row[$startcol + 5] !== null) ? (double) $row[$startcol + 5] : null;
            $this->dias = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
            $this->observaciones = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
            $this->archivo_uno = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
            $this->archivo_dos = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 10; // 10 = VacacionUsuarioPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating VacacionUsuario object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

        if ($this->aUsuario !== null && $this->usuario_id !== $this->aUsuario->getId()) {
            $this->aUsuario = null;
        }
    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(VacacionUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = VacacionUsuarioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

            $this->aUsuario = null;
        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(VacacionUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = VacacionUsuarioQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseVacacionUsuario:delete:pre') as $callable)
            {
              if (call_user_func($callable, $this, $con))
              {
                $con->commit();
                return;
              }
            }

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseVacacionUsuario:delete:post') as $callable)
                {
                  call_user_func($callable, $this, $con);
                }

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(VacacionUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseVacacionUsuario:save:pre') as $callable)
            {
              if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
              {
                  $con->commit();
                return $affectedRows;
              }
            }

            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseVacacionUsuario:save:post') as $callable)
                {
                  call_user_func($callable, $this, $con, $affectedRows);
                }

                VacacionUsuarioPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            // We call the save method on the following object(s) if they
            // were passed to this object by their coresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aUsuario !== null) {
                if ($this->aUsuario->isModified() || $this->aUsuario->isNew()) {
                    $affectedRows += $this->aUsuario->save($con);
                }
                $this->setUsuario($this->aUsuario);
            }

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = VacacionUsuarioPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . VacacionUsuarioPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(VacacionUsuarioPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`ID`';
        }
        if ($this->isColumnModified(VacacionUsuarioPeer::USUARIO_ID)) {
            $modifiedColumns[':p' . $index++]  = '`USUARIO_ID`';
        }
        if ($this->isColumnModified(VacacionUsuarioPeer::PERIODO)) {
            $modifiedColumns[':p' . $index++]  = '`PERIODO`';
        }
        if ($this->isColumnModified(VacacionUsuarioPeer::FECHA_INICIO)) {
            $modifiedColumns[':p' . $index++]  = '`FECHA_INICIO`';
        }
        if ($this->isColumnModified(VacacionUsuarioPeer::FECHA_FIN)) {
            $modifiedColumns[':p' . $index++]  = '`FECHA_FIN`';
        }
        if ($this->isColumnModified(VacacionUsuarioPeer::VALOR)) {
            $modifiedColumns[':p' . $index++]  = '`VALOR`';
        }
        if ($this->isColumnModified(VacacionUsuarioPeer::DIAS)) {
            $modifiedColumns[':p' . $index++]  = '`DIAS`';
        }
        if ($this->isColumnModified(VacacionUsuarioPeer::OBSERVACIONES)) {
            $modifiedColumns[':p' . $index++]  = '`OBSERVACIONES`';
        }
        if ($this->isColumnModified(VacacionUsuarioPeer::ARCHIVO_UNO)) {
            $modifiedColumns[':p' . $index++]  = '`ARCHIVO_UNO`';
        }
        if ($this->isColumnModified(VacacionUsuarioPeer::ARCHIVO_DOS)) {
            $modifiedColumns[':p' . $index++]  = '`ARCHIVO_DOS`';
        }

        $sql = sprintf(
            'INSERT INTO `vacacion_usuario` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`ID`':
                        $stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`USUARIO_ID`':
                        $stmt->bindValue($identifier, $this->usuario_id, PDO::PARAM_INT);
                        break;
                    case '`PERIODO`':
                        $stmt->bindValue($identifier, $this->periodo, PDO::PARAM_INT);
                        break;
                    case '`FECHA_INICIO`':
                        $stmt->bindValue($identifier, $this->fecha_inicio, PDO::PARAM_STR);
                        break;
                    case '`FECHA_FIN`':
                        $stmt->bindValue($identifier, $this->fecha_fin, PDO::PARAM_STR);
                        break;
                    case '`VALOR`':
                        $stmt->bindValue($identifier, $this->valor, PDO::PARAM_STR);
                        break;
                    case '`DIAS`':
                        $stmt->bindValue($identifier, $this->dias, PDO::PARAM_INT);
                        break;
                    case '`OBSERVACIONES`':
                        $stmt->bindValue($identifier, $this->observaciones, PDO::PARAM_STR);
                        break;
                    case '`ARCHIVO_UNO`':
                        $stmt->bindValue($identifier, $this->archivo_uno, PDO::PARAM_STR);
                        break;
                    case '`ARCHIVO_DOS`':
                        $stmt->bindValue($identifier, $this->archivo_dos, PDO::PARAM_STR);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
            $pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            // We call the validate method on the following object(s) if they
            // were passed to this object by their coresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aUsuario !== null) {
                if (!$this->aUsuario->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aUsuario->getValidationFailures());
                }
            }


            if (($retval = VacacionUsuarioPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }



            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = VacacionUsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getUsuarioId();
                break;
            case 2:
                return $this->getPeriodo();
                break;
            case 3:
                return $this->getFechaInicio();
                break;
            case 4:
                return $this->getFechaFin();
                break;
            case 5:
                return $this->getValor();
                break;
            case 6:
                return $this->getDias();
                break;
            case 7:
                return $this->getObservaciones();
                break;
            case 8:
                return $this->getArchivoUno();
                break;
            case 9:
                return $this->getArchivoDos();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
    {
        if (isset($alreadyDumpedObjects['VacacionUsuario'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['VacacionUsuario'][$this->getPrimaryKey()] = true;
        $keys = VacacionUsuarioPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getUsuarioId(),
            $keys[2] => $this->getPeriodo(),
            $keys[3] => $this->getFechaInicio(),
            $keys[4] => $this->getFechaFin(),
            $keys[5] => $this->getValor(),
            $keys[6] => $this->getDias(),
            $keys[7] => $this->getObservaciones(),
            $keys[8] => $this->getArchivoUno(),
            $keys[9] => $this->getArchivoDos(),
        );
        if ($includeForeignObjects) {
            if (null !== $this->aUsuario) {
                $result['Usuario'] = $this->aUsuario->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
        }

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = VacacionUsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setUsuarioId($value);
                break;
            case 2:
                $this->setPeriodo($value);
                break;
            case 3:
                $this->setFechaInicio($value);
                break;
            case 4:
                $this->setFechaFin($value);
                break;
            case 5:
                $this->setValor($value);
                break;
            case 6:
                $this->setDias($value);
                break;
            case 7:
                $this->setObservaciones($value);
                break;
            case 8:
                $this->setArchivoUno($value);
                break;
            case 9:
                $this->setArchivoDos($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = VacacionUsuarioPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setUsuarioId($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setPeriodo($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setFechaInicio($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setFechaFin($arr[$keys[4]]);
        if (array_key_exists($keys[5], $arr)) $this->setValor($arr[$keys[5]]);
        if (array_key_exists($keys[6], $arr)) $this->setDias($arr[$keys[6]]);
        if (array_key_exists($keys[7], $arr)) $this->setObservaciones($arr[$keys[7]]);
        if (array_key_exists($keys[8], $arr)) $this->setArchivoUno($arr[$keys[8]]);
        if (array_key_exists($keys[9], $arr)) $this->setArchivoDos($arr[$keys[9]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(VacacionUsuarioPeer::DATABASE_NAME);

        if ($this->isColumnModified(VacacionUsuarioPeer::ID)) $criteria->add(VacacionUsuarioPeer::ID, $this->id);
        if ($this->isColumnModified(VacacionUsuarioPeer::USUARIO_ID)) $criteria->add(VacacionUsuarioPeer::USUARIO_ID, $this->usuario_id);
        if ($this->isColumnModified(VacacionUsuarioPeer::PERIODO)) $criteria->add(VacacionUsuarioPeer::PERIODO, $this->periodo);
        if ($this->isColumnModified(VacacionUsuarioPeer::FECHA_INICIO)) $criteria->add(VacacionUsuarioPeer::FECHA_INICIO, $this->fecha_inicio);
        if ($this->isColumnModified(VacacionUsuarioPeer::FECHA_FIN)) $criteria->add(VacacionUsuarioPeer::FECHA_FIN, $this->fecha_fin);
        if ($this->isColumnModified(VacacionUsuarioPeer::VALOR)) $criteria->add(VacacionUsuarioPeer::VALOR, $this->valor);
        if ($this->isColumnModified(VacacionUsuarioPeer::DIAS)) $criteria->add(VacacionUsuarioPeer::DIAS, $this->dias);
        if ($this->isColumnModified(VacacionUsuarioPeer::OBSERVACIONES)) $criteria->add(VacacionUsuarioPeer::OBSERVACIONES, $this->observaciones);
        if ($this->isColumnModified(VacacionUsuarioPeer::ARCHIVO_UNO)) $criteria->add(VacacionUsuarioPeer::ARCHIVO_UNO, $this->archivo_uno);
        if ($this->isColumnModified(VacacionUsuarioPeer::ARCHIVO_DOS)) $criteria->add(VacacionUsuarioPeer::ARCHIVO_DOS, $this->archivo_dos);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(VacacionUsuarioPeer::DATABASE_NAME);
        $criteria->add(VacacionUsuarioPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of VacacionUsuario (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setUsuarioId($this->getUsuarioId());
        $copyObj->setPeriodo($this->getPeriodo());
        $copyObj->setFechaInicio($this->getFechaInicio());
        $copyObj->setFechaFin($this->getFechaFin());
        $copyObj->setValor($this->getValor());
        $copyObj->setDias($this->getDias());
        $copyObj->setObservaciones($this->getObservaciones());
        $copyObj->setArchivoUno($this->getArchivoUno());
        $copyObj->setArchivoDos($this->getArchivoDos());

        if ($deepCopy && !$this->startCopy) {
            // important: temporarily setNew(false) because this affects the behavior of
            // the getter/setter methods for fkey referrer objects.
            $copyObj->setNew(false);
            // store object hash to prevent cycle
            $this->startCopy = true;

            //unflag object copy
            $this->startCopy = false;
        } // if ($deepCopy)

        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return VacacionUsuario Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return VacacionUsuarioPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new VacacionUsuarioPeer();
        }

        return self::$peer;
    }

    /**
     * Declares an association between this object and a Usuario object.
     *
     * @param             Usuario $v
     * @return VacacionUsuario The current object (for fluent API support)
     * @throws PropelException
     */
    public function setUsuario(Usuario $v = null)
    {
        if ($v === null) {
            $this->setUsuarioId(NULL);
        } else {
            $this->setUsuarioId($v->getId());
        }

        $this->aUsuario = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Usuario object, it will not be re-added.
        if ($v !== null) {
            $v->addVacacionUsuario($this);
        }


        return $this;
    }


    /**
     * Get the associated Usuario object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Usuario The associated Usuario object.
     * @throws PropelException
     */
    public function getUsuario(PropelPDO $con = null)
    {
        if ($this->aUsuario === null && ($this->usuario_id !== null)) {
            $this->aUsuario = UsuarioQuery::create()->findPk($this->usuario_id, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aUsuario->addVacacionUsuarios($this);
             */
        }

        return $this->aUsuario;
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->usuario_id = null;
        $this->periodo = null;
        $this->fecha_inicio = null;
        $this->fecha_fin = null;
        $this->valor = null;
        $this->dias = null;
        $this->observaciones = null;
        $this->archivo_uno = null;
        $this->archivo_dos = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
        } // if ($deep)

        $this->aUsuario = null;
    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(VacacionUsuarioPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {

        // symfony_behaviors behavior
        if ($callable = sfMixer::getCallable('BaseVacacionUsuario:' . $name))
        {
          array_unshift($params, $this);
          return call_user_func_array($callable, $params);
        }


        return parent::__call($name, $params);
    }

}
