<?php


/**
 * Base class that represents a query for the 'licenciamiento' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 01/07/19 03:29:17
 *
 * @method LicenciamientoQuery orderById($order = Criteria::ASC) Order by the id column
 * @method LicenciamientoQuery orderByEmpresa($order = Criteria::ASC) Order by the empresa column
 * @method LicenciamientoQuery orderByMac($order = Criteria::ASC) Order by the mac column
 * @method LicenciamientoQuery orderByActivo($order = Criteria::ASC) Order by the activo column
 *
 * @method LicenciamientoQuery groupById() Group by the id column
 * @method LicenciamientoQuery groupByEmpresa() Group by the empresa column
 * @method LicenciamientoQuery groupByMac() Group by the mac column
 * @method LicenciamientoQuery groupByActivo() Group by the activo column
 *
 * @method LicenciamientoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method LicenciamientoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method LicenciamientoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method Licenciamiento findOne(PropelPDO $con = null) Return the first Licenciamiento matching the query
 * @method Licenciamiento findOneOrCreate(PropelPDO $con = null) Return the first Licenciamiento matching the query, or a new Licenciamiento object populated from the query conditions when no match is found
 *
 * @method Licenciamiento findOneById(int $id) Return the first Licenciamiento filtered by the id column
 * @method Licenciamiento findOneByEmpresa(string $empresa) Return the first Licenciamiento filtered by the empresa column
 * @method Licenciamiento findOneByMac(string $mac) Return the first Licenciamiento filtered by the mac column
 * @method Licenciamiento findOneByActivo(boolean $activo) Return the first Licenciamiento filtered by the activo column
 *
 * @method array findById(int $id) Return Licenciamiento objects filtered by the id column
 * @method array findByEmpresa(string $empresa) Return Licenciamiento objects filtered by the empresa column
 * @method array findByMac(string $mac) Return Licenciamiento objects filtered by the mac column
 * @method array findByActivo(boolean $activo) Return Licenciamiento objects filtered by the activo column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseLicenciamientoQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseLicenciamientoQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Licenciamiento', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new LicenciamientoQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     LicenciamientoQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return LicenciamientoQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof LicenciamientoQuery) {
            return $criteria;
        }
        $query = new LicenciamientoQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Licenciamiento|Licenciamiento[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = LicenciamientoPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(LicenciamientoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Licenciamiento A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `EMPRESA`, `MAC`, `ACTIVO` FROM `licenciamiento` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Licenciamiento();
            $obj->hydrate($row);
            LicenciamientoPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Licenciamiento|Licenciamiento[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Licenciamiento[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return LicenciamientoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(LicenciamientoPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return LicenciamientoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(LicenciamientoPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return LicenciamientoQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(LicenciamientoPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the empresa column
     *
     * Example usage:
     * <code>
     * $query->filterByEmpresa('fooValue');   // WHERE empresa = 'fooValue'
     * $query->filterByEmpresa('%fooValue%'); // WHERE empresa LIKE '%fooValue%'
     * </code>
     *
     * @param     string $empresa The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return LicenciamientoQuery The current query, for fluid interface
     */
    public function filterByEmpresa($empresa = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($empresa)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $empresa)) {
                $empresa = str_replace('*', '%', $empresa);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(LicenciamientoPeer::EMPRESA, $empresa, $comparison);
    }

    /**
     * Filter the query on the mac column
     *
     * Example usage:
     * <code>
     * $query->filterByMac('fooValue');   // WHERE mac = 'fooValue'
     * $query->filterByMac('%fooValue%'); // WHERE mac LIKE '%fooValue%'
     * </code>
     *
     * @param     string $mac The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return LicenciamientoQuery The current query, for fluid interface
     */
    public function filterByMac($mac = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($mac)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $mac)) {
                $mac = str_replace('*', '%', $mac);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(LicenciamientoPeer::MAC, $mac, $comparison);
    }

    /**
     * Filter the query on the activo column
     *
     * Example usage:
     * <code>
     * $query->filterByActivo(true); // WHERE activo = true
     * $query->filterByActivo('yes'); // WHERE activo = true
     * </code>
     *
     * @param     boolean|string $activo The value to use as filter.
     *              Non-boolean arguments are converted using the following rules:
     *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return LicenciamientoQuery The current query, for fluid interface
     */
    public function filterByActivo($activo = null, $comparison = null)
    {
        if (is_string($activo)) {
            $activo = in_array(strtolower($activo), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
        }

        return $this->addUsingAlias(LicenciamientoPeer::ACTIVO, $activo, $comparison);
    }

    /**
     * Exclude object from result
     *
     * @param   Licenciamiento $licenciamiento Object to remove from the list of results
     *
     * @return LicenciamientoQuery The current query, for fluid interface
     */
    public function prune($licenciamiento = null)
    {
        if ($licenciamiento) {
            $this->addUsingAlias(LicenciamientoPeer::ID, $licenciamiento->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
