<?php



/**
 * Skeleton subclass for representing a row from the 'recibo_encabezado' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 08/06/18 23:12:33
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ReciboEncabezado extends BaseReciboEncabezado
{
}
