# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  .datos:
    conexion_carga:  
      'servidor': 'localhost'
      'base_datos' : 'adminblog'
      'usuario' : 'adminblog'
      'clave' : 'adminblog$123'  
      'ruta': '/home/controlgospelrev/public_html/web/uploads/'
      'url': 'http://control.gospelrevolution.group/uploads/'
    hora:
      '00': '00'
      '01': '01'
      '02': '02'
      '03': '03'
      '04': '04'
      '05': '05'
      '06': '06'
      '07': '07'
      '08': '08'
      '09': '09'
      '10': '10'
      '11': '11'
      '12': '12'
      '13': '13'
      '14': '14'
      '15': '15'
      '16': '16'
      '17': '17'
      '18': '18'
      '19': '19'
      '20': '20'
      '21': '21'
      '22': '22'
      '23': '23'