<?php

/**
 * Skeleton subclass for performing query and update operations on the 'usuario' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Fri Sep 20 13:26:47 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class UsuarioQuery extends BaseUsuarioQuery {

    static public function validaUsuario($u, $c) {

        $intentos = 10; // sfConfig::get("app_seguridad_intentos",3);
        $segundos_bloqueo = 10; // sfConfig::get("app_seguridad_tiempo",60);
        $hora_bloqueo = date('Y-m-d H:i:s', mktime(date('H'), date('i'), date('s') + $segundos_bloqueo, date('m'), date('d'), date('Y')));
        $usuario = UsuarioQuery::create()
                ->filterByActivo(true)
                ->filterByUsuario($u)
                ->findOne();

        $msg = null;
        if ($usuario) {
            if ($usuario->getClave() == $c) {
                
            } else {
                $msg = 'Usuario/Clave Inválido';
                $usuario = null;
            }
        } else {
            $usuario = null;
            $msg = 'Usuario/Clave Inválido';
        }
        sfContext::getInstance()->getUser()->setFlash('login', $msg);
        return $usuario;
    }

    static function menuUsuario($usuario_id) {

    }
  static function getEmpresaSeleccionada($tabla = null) {
        $retorno = false;
        if (sfContext::hasInstance()) {
            $user = sfContext::getInstance()->getUser();
            if ($user->isAuthenticated()) {
                if ($user->getAttribute('filtro', null, $tabla) || is_null($user->getAttribute('filtro', null, $tabla))) {
                    $empresaSeleccion = $user->getAttribute('usuario', null, 'empresa');
                    if ($empresaSeleccion) {
                        $retorno = $empresaSeleccion;
                    }
                } else {
                    $user->setAttribute('filtro', true, $tabla);
                }
            }
        }
        return $retorno;
    }

    static function getUsuario($tabla = null) {
        $retorno = false;
        if (sfContext::hasInstance()) {
            $user = sfContext::getInstance()->getUser();
            if ($user->isAuthenticated()) {
                $usuarioSeleccionado = $user->getAttribute('usuario', null, 'seguridad');
                if ($usuarioSeleccionado) {
                    $retorno = $usuarioSeleccionado;
                }
            }
        }
        return $retorno;
    }

}
