<?php



/**
 * Skeleton subclass for performing query and update operations on the 'usuario_horario' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 11/16/18 21:49:01
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class UsuarioHorarioPeer extends BaseUsuarioHorarioPeer
{
}
