generator:
  class: sfPropelGenerator
  param:
    model_class:           Parametro
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Parametro
    plural:                Parametros
    route_prefix:          parametro
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
          activo:
              attributes:
                  class:    form-group check-radio
          nombre:
              label:       Nombre
              attributes:
                  class:    form-control input-xlarge    
          codigo:
              attributes:
                  class:    form-control input-medium
          precio_click:
              attributes:
                  class:    form-control input-medium                  
          precio_impresion:
              attributes:
                  class:    form-control input-medium                  
          precio_mil_impresion:
              attributes:
                  class:    form-control input-medium                  
 
      list: 
        title:             Parametros
        display:           [codigo,_logo,precio_click,precio_impresion]
      filter:
        display:           [slogan,logo]
      form:
        display:           [precio_click,precio_impresion,precio_mil_impresion,slogan,logo]
      edit:
        title:             Editar  "%%CODIGO%%"
      new:
        title:             Nuevo
