generator:
  class: sfPropelGenerator
  param:
    model_class:           Parametro
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Parametro
    plural:                Parametros
    route_prefix:          parametro
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
          activo:
              attributes:
                  class:    form-group check-radio
          nombre:
              label:       Nombre
              attributes:
                  class:    form-control input-xlarge    
          codigo:
              attributes:
                  class:    form-control input-medium
          puerto_correo:  
              attributes:
                  class:    form-control  input-medium    
          smtp_correo:  
              attributes:
                  class:    form-control  input-medium   
          usuario_correo:  
              attributes:
                  class:    form-control  input-medium   
          clave_correo:  
              attributes:
                  class:    form-control  input-medium                     
          correo_notifica:
              attributes:
                  class:    form-control  input-medium                     
               
      list: 
        title:             Parametros
        display:           [codigo,slogan,_logo]
      filter:
        display:           [slogan,logo]
      form:
        display:           [codigo,slogan,logo,usuario_correo,clave_correo,puerto_correo,smtp_correo,correo_notifica]
      edit:
        title:             Editar  "%%CODIGO%%"
      new:
        title:             Nuevo
